export enum APPOINTMENT_KEYS {
  ACCOUNT = "ACCOUNT",
  APPOINTMENT = "APPOINTMENT",
  MODERATOR = "MODERATOR",
  DATE_MEETING = "DATE_MEETING",
  TIME_MEETING = "TIME_MEETING",
  SCHEDULE = "SCHEDULE",
}
